#!/usr/bin/env bash
set -e

ROOT=$(git rev-parse --show-toplevel)

commit_hash=$(git rev-parse HEAD)
commit_date=$(git show -s --format=%ci HEAD)

OUT="$ROOT/src/Lution/modules/configcheck/VERSION.py"

cat > "$OUT" <<EOF
# AUTO GENARATED, DO NOT TRY TO MODIFY
# sigmas
GIT_COMMITT = "$commit_hash"
COMMIT_DATE = "$commit_date"

from github import Github

g = Github()
repo = g.get_repo("lutionhq/lution")
ltcommit = repo.get_commits()[1]
if ltcommit.sha == GIT_COMMITT:
    GIT_COMMIT = f"{GIT_COMMITT} (outdated)"
else:
    GIT_COMMIT = GIT_COMMITT

EOF

git add "$OUT"
