name: Build Lution AppImage

on:
  push:
    branches: [latest]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies to AppDir
        run: |
          mkdir -p AppDir/usr/site-packages
          pip install --target=AppDir/usr/site-packages -r src/Lution/requirements.txt

      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          cp -r src/Lution AppDir/usr/bin/Lution

      - name: Create AppRun
        run: |
          echo '#!/bin/bash' > AppDir/AppRun
          echo 'HERE="$(dirname "$(readlink -f "$0")")"' >> AppDir/AppRun
          echo 'export PYTHONPATH="$HERE/usr/site-packages"' >> AppDir/AppRun
          echo 'python3 -m streamlit run "$HERE/usr/bin/Lution/main.py" --server.headless true' >> AppDir/AppRun
          chmod +x AppDir/AppRun

      - name: Create desktop file
        run: |
          echo '[Desktop Entry]' > AppDir/lution.desktop
          echo 'Type=Application' >> AppDir/lution.desktop
          echo 'Name=Lution' >> AppDir/lution.desktop
          echo 'Exec=AppRun' >> AppDir/lution.desktop
          echo 'Icon=icon' >> AppDir/lution.desktop
          echo 'Categories=Utility;' >> AppDir/lution.desktop
          echo 'Terminal=false' >> AppDir/lution.desktop

      - name: Add icon
        run: |
          cp src/Lution/files/lution1.png AppDir/icon.png || echo "No icon found"

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Install libfuse2
        run: |
          sudo apt update
          sudo apt install -y libfuse2

      - name: Build AppImage
        run: |
          ./appimagetool-x86_64.AppImage AppDir

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: LutionApp
          path: Lution-x86_64.AppImage
