name: fuck it, let zip everything up like github and call it a day

on:
  push:
    branches: [latest]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create portable zip folder
        run: |
          mkdir LutionPortable
          cp run.sh requirements.txt LutionPortable/
          cp -r src LutionPortable/

      - name: Create ZIP archive
        run: |
          zip -r LutionPortable.zip LutionPortable

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LutionPortable
          path: LutionPortable.zip
